In [1]:
import numpy

In [2]:
numpy.mean([1, 2, 3, 4, 5])

3.0

In [3]:
import numpy as np

In [4]:
np.mean([1, 2, 3, 4, 5])

3.0

In [5]:
pares = np.array([2, 4, 6, 8])

In [6]:
pares

array([2, 4, 6, 8])

In [7]:
temperaturas = np.array([10.1, 14.6, 18.3, 20.3])

In [8]:
temperaturas

array([10.1, 14.6, 18.3, 20.3])

In [9]:
temperaturas[0]

10.1

In [10]:
temperaturas[2:]

array([18.3, 20.3])

In [11]:
np.median(temperaturas)

16.45

In [12]:
np.std(temperaturas)

3.886756359742659

In [13]:
np.min(temperaturas)

10.1

In [14]:
np.max(temperaturas)

20.3

In [15]:
np.mean?

Signature: np.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
Docstring:
Compute the arithmetic mean along the specified axis.

Returns the average of the array elements.  The average is taken over
the flattened array by default, otherwise over the specified axis.
`float64` intermediate and return values are used for integer inputs.

Parameters
----------
a : array_like
    Array containing numbers whose mean is desired. If `a` is not an
    array, a conversion is attempted.
axis : None or int or tuple of ints, optional
    Axis or axes along which the means are computed. The default is to
    compute the mean of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a mean is performed over multiple axes,
    instead of a single axis or all the axes as before.
dtype : data-type, optional
    Type to use in computing the mean.  For integer inputs, the default
    is `float64`; for floating point inputs, it is the same as the
    input dtype.
ou

In [16]:
temperaturas_f = np.array([30.3, 20.1, 46.5, 34.1, 42.3])

In [17]:
temperaturas_f

array([30.3, 20.1, 46.5, 34.1, 42.3])

In [18]:
temperaturas_c = 5 / 9 * (temperaturas_f - 32)

In [19]:
temperaturas_c

array([-0.94444444, -6.61111111,  8.05555556,  1.16666667,  5.72222222])

In [20]:
precios = np.array([100, 200, 120, 98, 65, 3])
cantidades = np.array([2, 1, 3, 4, 9, 5])

In [21]:
precios

array([100, 200, 120,  98,  65,   3])

In [22]:
cantidades

array([2, 1, 3, 4, 9, 5])

In [23]:
costos = precios * cantidades

In [24]:
costos

array([200, 200, 360, 392, 585,  15])

In [25]:
total = np.sum(costos)

In [26]:
total

1752

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

a + b

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [28]:
np.dot([1, 2], [-1, 1])

1

In [29]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [30]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_2d[0, 1]

2

In [32]:
array_2d[:, 1]

array([2, 5])

In [33]:
array_2d.size

6

In [35]:
shape = array_2d.shape

In [36]:
shape

(2, 3)

In [37]:
type(shape)

tuple

In [38]:
shape[0]

2

In [39]:
shape[1]

3

In [40]:
shape[0] = 100

TypeError: 'tuple' object does not support item assignment

In [41]:
# Esto es un comentario
a = 2

In [42]:
a = 2  # esto es un comentario

In [43]:
np.sqrt(2)

1.4142135623730951

In [44]:
np.sin(np.pi / 2)

1.0

In [45]:
np.cos(np.pi / 2)

6.123233995736766e-17

In [46]:
np.exp(1)

2.718281828459045

In [47]:
np.log(1)

0.0

In [48]:
np.log(np.e)

1.0

In [49]:
cuadrados = np.array([4, 9, 16, 25, 36, 49, 64, 81])
np.sqrt(cuadrados)

array([2., 3., 4., 5., 6., 7., 8., 9.])